const app = document.querySelector('#app');
const toast = document.querySelector('#toast');
const stateKey = 'pedeia-state-v3';
const sessionKey = 'pedeia-merchant-session';
const emptyState = { view: 'dashboard', merchant: null, shop: null, categories: [], products: [], orders: [], ratings: [], messages: [], cart: [] };
let state = readState();

function readState() { try { return { ...emptyState, ...(JSON.parse(localStorage.getItem(stateKey)) || {}) }; } catch { return structuredClone(emptyState); } }
function save() { localStorage.setItem(stateKey, JSON.stringify(state)); }
function money(value) { return Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }); }
function esc(value) { return String(value ?? '').replace(/[&<>\"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[char])); }
function notify(message) { toast.textContent = message; toast.classList.add('show'); clearTimeout(notify.timer); notify.timer = setTimeout(() => toast.classList.remove('show'), 2500); }
function saveRender() { save(); render(); }
function slug(value) { return String(value).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'minha-loja'; }
function shopLink() { return `${location.origin}${location.pathname}?loja=${encodeURIComponent(state.shop.publicId)}`; }
function publicShop() { return new URLSearchParams(location.search).get('loja'); }
function loggedIn() { return sessionStorage.getItem(sessionKey) === 'active'; }
function brand() { return '<a class="brand" href="/"><span class="brand-mark">P</span><span>Pede<span>IA</span></span></a>'; }
function render() { if (publicShop() !== null) return publicShop() === state.shop?.publicId ? shopView() : missingView(); if (!loggedIn() || !state.merchant || !state.shop) return authView(); dashboard(); }

function authView() {
  app.innerHTML = `<main class="auth-screen"><div class="auth-art">${brand()}<div class="art-copy"><span class="eyebrow">PARA QUEM FAZ ACONTECER</span><h1>Seu negócio.<br><em>Do seu jeito.</em></h1><p>Organize sua loja, receba pedidos e deixe cada cliente com vontade de voltar.</p><div class="art-orbit"><span>?x?</span><span>?x</span><span>?S?</span></div></div></div><section class="auth-card"><span class="eyebrow">PAINEL DO COMERCIANTE</span><h2>Vamos começar?</h2><p>Crie sua conta e coloque sua loja no ar.</p><div class="auth-tabs"><button class="selected" data-auth="register">Criar conta</button><button data-auth="login">Entrar</button></div><form id="register-form" class="auth-form"><label>Seu nome<input name="name" required placeholder="Como podemos chamar você?"></label><label>E-mail<input name="email" type="email" required placeholder="voce@email.com"></label><label>Senha<input name="password" type="password" minlength="6" required placeholder="Mínimo de 6 caracteres"></label><label>Nome do comércio<input name="shopName" required placeholder="Ex.: Brasa & Massa"></label><label>Tipo de comércio<select name="shopType"><option>Restaurante</option><option>Lanchonete</option><option>Hamburgueria</option><option>Pizzaria</option><option>Loja</option><option>Outro comércio</option></select></label><button class="primary-button auth-submit">Criar minha conta ? </button></form><form id="login-form" class="auth-form hidden"><label>E-mail<input name="email" type="email" required placeholder="voce@email.com"></label><label>Senha<input name="password" type="password" required placeholder="Sua senha"></label><button class="primary-button auth-submit">Entrar no painel ? </button></form><p class="auth-note">O cliente não cria conta. Ele acessa sua loja pelo link exclusivo.</p></section></main>`;
  document.querySelectorAll('[data-auth]').forEach(button => button.onclick = () => switchAuth(button.dataset.auth));
  document.querySelector('#register-form').onsubmit = register;
  document.querySelector('#login-form').onsubmit = login;
}
function switchAuth(type) { document.querySelectorAll('[data-auth]').forEach(button => button.classList.toggle('selected', button.dataset.auth === type)); document.querySelector('#register-form').classList.toggle('hidden', type !== 'register'); document.querySelector('#login-form').classList.toggle('hidden', type !== 'login'); }
function register(event) { event.preventDefault(); if (state.merchant) return notify('Esta demonstração já possui uma conta. Entre com seus dados.'); const data = new FormData(event.currentTarget); const shopName = String(data.get('shopName')).trim(); const shopSlug = slug(shopName); state.merchant = { name: String(data.get('name')).trim(), email: String(data.get('email')).trim().toLowerCase(), password: data.get('password') }; state.shop = { name: shopName, type: data.get('shopType'), publicId: `${shopSlug}-${Math.random().toString(36).slice(2, 7)}`, description: 'Adicione uma descrição para apresentar seu comércio.', photo: null, isOpen: true }; state.categories = []; state.products = []; state.orders = []; state.ratings = []; state.messages = []; sessionStorage.setItem(sessionKey, 'active'); saveRender(); notify('Conta criada. Agora personalize sua loja.'); }
function login(event) { event.preventDefault(); const data = new FormData(event.currentTarget); if (!state.merchant || String(data.get('email')).trim().toLowerCase() !== state.merchant.email || data.get('password') !== state.merchant.password) return notify('E-mail ou senha inválidos.'); sessionStorage.setItem(sessionKey, 'active'); render(); }

function nav(view, icon, text, count = '') { return `<button class="${state.view === view ? 'active' : ''}" data-view="${view}"><span>${icon}</span>${text}${count !== '' ? `<b>${count}</b>` : ''}</button>`; }
function dashboard() {
  const revenue = state.orders.reduce((sum, order) => sum + order.total, 0); const rating = state.ratings.length ? (state.ratings.reduce((sum, item) => sum + item.value, 0) / state.ratings.length).toFixed(1) : '?';
  const page = state.view;
  app.innerHTML = `<div class="shell"><aside class="sidebar">${brand()}<div class="shop-mini"><div class="shop-avatar">${state.shop.photo ? `<img src="${state.shop.photo}" alt="">` : esc(state.shop.name[0])}</div><div><strong>${esc(state.shop.name)}</strong><small>${state.shop.isOpen ? ' Aberta agora' : '?9 Fechada'}</small></div><button class="toggle-store ${state.shop.isOpen ? 'on' : 'off'}" data-action="toggle-open"><span></span></button></div><div class="persistent-link"><div><span>LINK DA SUA LOJA</span><strong>${esc(shopLink().replace(/^https?:\/\//, ''))}</strong></div><button data-action="copy">?x</button></div><nav class="side-nav">${nav('dashboard', '?R', 'Visão geral')}${nav('orders', '', 'Pedidos', state.orders.length)}${nav('menu', '', 'Cardápio')}${nav('categories', '+', 'Categorias')}${nav('chat', '?R', 'Conversas')}${nav('settings', '?a"', 'Minha loja')}</nav><div class="sidebar-bottom"><button class="help-link" data-action="copy">?  Compartilhar loja</button><div class="profile-chip"><div class="profile-photo">${esc(state.merchant.name.slice(0, 2).toUpperCase())}</div><div><strong>${esc(state.merchant.name)}</strong><small>Comerciante</small></div><button class="logout-link" data-action="logout">Sair</button></div></div></aside><main class="main-content"><header class="topbar"><div class="breadcrumb">PedeIA <span>/</span> ${page}</div><button class="outline-button" data-action="open-shop">?  Ver minha loja</button></header>${page === 'dashboard' ? home(revenue, rating) : page === 'orders' ? orders() : page === 'menu' ? menu() : page === 'categories' ? categories() : page === 'chat' ? chat() : settings()}</main></div>`;
  bindDashboard();
}
function empty(title, text) { return `<div class="empty-panel"><span>?S?</span><strong>${title}</strong><small>${text}</small></div>`; }
function home(revenue, rating) { return `<section class="page-intro"><div><p class="eyebrow">PAINEL DA SUA LOJA</p><h1>Olá, ${esc(state.merchant.name.split(' ')[0])} <span>?S?</span></h1><p class="intro-copy">Tudo que acontece no seu comércio, em um só lugar.</p></div><button class="primary-button" data-action="new-product">+ Novo produto</button></section><section class="stats-grid"><article class="stat-card warm"><span>Pedidos hoje</span><strong>${state.orders.length}</strong><small>Dados dos seus pedidos</small></article><article class="stat-card"><span>Vendas hoje</span><strong>${money(revenue)}</strong><small>Total dos pedidos recebidos</small></article><article class="stat-card"><span>Itens no cardápio</span><strong>${state.products.length}</strong><small>${state.products.filter(item => item.available).length} disponíveis agora</small></article><article class="stat-card"><span>Avaliação média</span><strong>${rating}</strong><small>${state.ratings.length} avaliações reais</small></article></section><section class="dashboard-grid"><article class="panel"><div class="panel-heading"><div><h2>Pedidos recentes</h2><p>${state.orders.length ? `Você tem <b>${state.orders.length} pedidos</b> para acompanhar.` : 'Quando chegar um pedido, ele aparecerá aqui.'}</p></div><button class="text-button" data-view="orders">Ver todos ? </button></div>${state.orders.length ? state.orders.slice(-5).reverse().map(orderRow).join('') : empty('Ainda não há pedidos', 'Compartilhe o link da sua loja para começar a vender.')}</article><article class="panel link-panel"><p class="eyebrow">LINK EXCLUSIVO DA SUA LOJA</p><h2>Seu comércio a um clique.</h2><p>O cliente não cria conta. Copie e envie pelo WhatsApp.</p><div class="link-box"><span>${esc(shopLink().replace(/^https?:\/\//, ''))}</span><button data-action="copy">?x</button></div><button class="share-button" data-action="copy">?  Copiar link</button></article></section>`; }
function orderRow(order) { return `<div class="order-row"><div class="order-number">${esc(order.id)}</div><div class="order-person"><strong>${esc(order.customer)}</strong><small>${esc(order.time || 'agora')}</small></div><strong class="order-total">${money(order.total)}</strong><span class="status">${esc(order.status)}</span><button class="row-arrow" data-action="open-chat">⬺</button></div>`; }
function orders() { return `<section class="page-intro"><div><p class="eyebrow">PEDIDOS RECEBIDOS PELO SEU LINK</p><h1>Pedidos</h1><p class="intro-copy">Acompanhe cada cliente até a entrega.</p></div></section><section class="panel full-panel"><div class="filter-row"><div class="filter active">Todos <b>${state.orders.length}</b></div><div class="filter">Aguardando <b>${state.orders.filter(item => item.status === 'Aguardando').length}</b></div><div class="filter">Em preparo <b>${state.orders.filter(item => item.status === 'Em preparo').length}</b></div></div>${state.orders.length ? state.orders.map(order => `${orderRow(order)}<div class="order-note">${order.notes ? `Observação: ${esc(order.notes)}` : 'Sem observações'}<button class="order-action" data-action="advance-order" data-id="${order.id}">Atualizar status</button></div>`).join('') : empty('Nenhum pedido recebido', 'Os pedidos feitos pelos clientes aparecerão aqui.')}</section>`; }
function menu() { return `<section class="page-intro"><div><p class="eyebrow">PRODUTOS E DISPONIBILIDADE</p><h1>Cardápio</h1><p class="intro-copy">Adicione fotos, descrições, preços e organize por categoria.</p></div><button class="primary-button" data-action="new-product">+ Novo produto</button></section><section class="panel full-panel"><div class="menu-toolbar"><div class="category-tabs">${state.categories.map(category => `<button>${esc(category)}</button>`).join('')}<button class="add-category" data-view="categories">+ Criar categoria</button></div><span class="muted">${state.products.length} produtos</span></div>${state.products.length ? state.products.map(product => `<div class="manage-row"><span class="manage-emoji">${product.photo ? `<img src="${product.photo}" alt="">` : product.emoji}</span><div><strong>${esc(product.name)}</strong><small>${esc(product.category)} · ${esc(product.description)}</small></div><b>${money(product.price)}</b><label class="switch"><input type="checkbox" data-product="${product.id}" ${product.available ? 'checked' : ''}><span></span></label><button class="dots" data-action="edit-product" data-id="${product.id}">?S}</button></div>`).join('') : empty('Seu cardápio está vazio', 'Crie uma categoria e adicione seu primeiro produto.')}</section>`; }
function categories() { return `<section class="page-intro"><div><p class="eyebrow">ORGANIZE SEU CARDÁPIO</p><h1>Categorias</h1><p class="intro-copy">Crie abas para refris, sucos, hambúrgueres, tapiocas e mais.</p></div><button class="primary-button" data-action="new-category">+ Nova categoria</button></section><section class="category-layout"><article class="panel category-create"><div class="category-icon">+</div><h2>Uma categoria para cada desejo</h2><p>Ajude o cliente a encontrar o que quer.</p><button class="primary-button" data-action="new-category">Criar categoria</button></article><article class="panel">${state.categories.length ? state.categories.map((category, index) => `<div class="category-row"><span>${String(index + 1).padStart(2, '0')}</span><strong>${esc(category)}</strong><small>${state.products.filter(item => item.category === category).length} produtos</small><button data-action="remove-category" data-category="${esc(category)}">?</button></div>`).join('') : empty('Nenhuma categoria criada', 'Comece criando a primeira aba.')}</article></section>`; }
function settings() { return `<section class="page-intro"><div><p class="eyebrow">A EXPERIENCIA COME?!A AQUI</p><h1>Minha loja</h1><p class="intro-copy">Personalize como seus clientes conhecem seu comércio.</p></div><button class="primary-button" data-action="copy">?  Copiar link</button></section><section class="settings-grid"><article class="panel shop-editor"><div class="editor-cover"><span>PedeIA</span></div><div class="editor-body"><div class="editor-avatar">${state.shop.photo ? `<img src="${state.shop.photo}" alt="">` : esc(state.shop.name[0])}</div><label>Foto da loja<input type="file" accept="image/*" data-shop-photo></label><label>Nome da loja<input data-setting="name" value="${esc(state.shop.name)}"></label><label>Tipo de comércio<input data-setting="type" value="${esc(state.shop.type)}"></label><label>Descrição<textarea data-setting="description">${esc(state.shop.description)}</textarea></label><button class="primary-button" data-action="save-shop">Salvar alterações</button></div></article><article class="panel preview-panel"><p class="eyebrow">SEU LINK PERMANENTE</p><div class="settings-link"><strong>${esc(shopLink())}</strong><button class="primary-button" data-action="copy">Copiar link</button><small>Esse link identifica somente sua loja. O cliente acessa sem cadastro.</small></div></article></section>`; }
function chat() { return `<section class="page-intro"><div><p class="eyebrow">CONVERSE COM QUEM PEDIU</p><h1>Conversas</h1><p class="intro-copy">Tire dúvidas e acompanhe seus clientes.</p></div></section><section class="panel chat-panel"><div class="chat-header"><div class="profile-photo">C</div><strong>Clientes da sua loja</strong></div><div class="chat-messages">${state.messages.length ? state.messages.map(message => `<div class="message ${message.from === 'merchant' ? 'mine' : ''}">${esc(message.text)}<small>${esc(message.time)}</small></div>`).join('') : empty('Nenhuma conversa ainda', 'As mensagens aparecerão aqui.')}</div><form class="chat-compose"><input name="message" required placeholder="Escreva uma mensagem..."><button>Enviar</button></form></section>`; }

function shopView() { const total = state.cart.reduce((sum, item) => sum + item.price * item.quantity, 0); app.innerHTML = `<div class="customer-app"><header class="customer-header">${brand()}<button class="chat-shop-button" data-action="customer-chat">?R Falar com a loja</button></header><section class="store-hero">${state.shop.photo ? `<img class="store-photo" src="${state.shop.photo}" alt="">` : `<div class="store-avatar-big">${esc(state.shop.name[0])}</div>`}<div><span class="open-pill">${state.shop.isOpen ? ' Aberta agora' : '?9 Fechada'}</span><h1>${esc(state.shop.name)}</h1><p>${esc(state.shop.description)}</p><small>${esc(state.shop.type)} · Entrega e retirada</small></div></section><nav class="customer-categories">${state.categories.map(category => `<a href="#${encodeURIComponent(category)}">${esc(category)}</a>`).join('')}</nav><main class="customer-menu">${state.categories.map(category => `<section id="${encodeURIComponent(category)}"><div class="category-heading"><h2>${esc(category)}</h2><span>${state.products.filter(item => item.category === category && item.available).length} opções</span></div><div class="customer-products">${state.products.filter(item => item.category === category && item.available).map(customerProduct).join('')}</div></section>`).join('')}${!state.categories.length ? '<div class="customer-empty"><strong>O cardápio está sendo preparado.</strong><small>Volte em breve.</small></div>' : ''}</main><button class="floating-cart ${state.cart.length ? '' : 'empty-floating'}" data-action="open-cart">?x: ${state.cart.length ? `<span>${state.cart.reduce((sum, item) => sum + item.quantity, 0)} itens</span><strong>Ver sacola</strong><b>${money(total)}</b>` : 'Sua sacola'}</button></div>`; document.querySelectorAll('[data-action]').forEach(button => button.onclick = handleAction); }
function customerProduct(product) { return `<article class="customer-product"><div class="food-image">${product.photo ? `<img src="${product.photo}" alt="">` : product.emoji}</div><div class="customer-product-info"><h3>${esc(product.name)}</h3><p>${esc(product.description)}</p><strong>${money(product.price)}</strong></div><button class="add-food" data-action="add-cart" data-id="${product.id}">+</button></article>`; }
function missingView() { app.innerHTML = `<main class="missing-shop">${brand()}<div><div class="missing-icon">?R</div><h1>Essa loja não foi encontrada.</h1><p>Confira se o link está completo ou peça um novo link ao comércio.</p><a class="primary-button" href="/">Voltar ao PedeIA</a></div></main>`; }

function bindDashboard() { document.querySelectorAll('[data-view]').forEach(button => button.onclick = () => { state.view = button.dataset.view; saveRender(); }); document.querySelectorAll('[data-action]').forEach(button => button.onclick = handleAction); document.querySelectorAll('[data-product]').forEach(input => input.onchange = () => { state.products.find(item => String(item.id) === input.dataset.product).available = input.checked; saveRender(); }); document.querySelector('.chat-compose')?.addEventListener('submit', sendMessage); document.querySelector('[data-shop-photo]')?.addEventListener('change', event => fileData(event.target.files[0], photo => { state.shop.photo = photo; saveRender(); })); }
function handleAction(event) { const button = event.currentTarget; const action = button.dataset.action; if (action === 'new-category') return categoryDialog(); if (action === 'new-product' || action === 'edit-product') return productDialog(button.dataset.id); if (action === 'remove-category') { state.categories = state.categories.filter(item => item !== button.dataset.category); state.products = state.products.filter(item => item.category !== button.dataset.category); return saveRender(); } if (action === 'toggle-open') { state.shop.isOpen = !state.shop.isOpen; return saveRender(); } if (action === 'save-shop') { document.querySelectorAll('[data-setting]').forEach(input => { state.shop[input.dataset.setting] = input.value.trim(); }); return saveRender(); } if (action === 'logout') { sessionStorage.removeItem(sessionKey); return render(); } if (action === 'copy' || action === 'share') return navigator.clipboard.writeText(shopLink()).then(() => notify('Link copiado para enviar no WhatsApp')); if (action === 'open-shop') return window.open(shopLink(), '_blank', 'noopener'); if (action === 'advance-order') { const order = state.orders.find(item => item.id === button.dataset.id); order.status = order.status === 'Aguardando' ? 'Em preparo' : order.status === 'Em preparo' ? 'Pronto' : 'Entregue'; return saveRender(); } if (action === 'add-cart') { const product = state.products.find(item => String(item.id) === button.dataset.id); const item = state.cart.find(entry => entry.id === product.id); if (item) item.quantity++; else state.cart.push({ ...product, quantity: 1, notes: '' }); save(); return shopView(); } if (action === 'open-cart') return cartDialog(); if (action === 'customer-chat') return customerChat(); }
function dialog(content) { const overlay = document.createElement('div'); overlay.className = 'cart-overlay dialog-overlay'; overlay.innerHTML = `<div class="cart-modal dialog-modal"><button class="modal-close">?</button>${content}</div>`; overlay.querySelector('.modal-close').onclick = closeDialog; overlay.onclick = event => { if (event.target === overlay) closeDialog(); }; document.body.appendChild(overlay); }
function closeDialog() { document.querySelector('.dialog-overlay')?.remove(); }
function categoryDialog() { dialog(`<div class="dialog-head"><span class="category-icon">+</span><h2>Nova categoria</h2><p>Crie uma aba para organizar seus produtos.</p></div><form id="category-form" class="dialog-form"><label>Nome da categoria<input name="name" required placeholder="Ex.: Tapiocas"></label><button class="primary-button">Criar categoria</button></form>`); document.querySelector('#category-form').onsubmit = event => { event.preventDefault(); const name = new FormData(event.currentTarget).get('name').trim(); if (name && !state.categories.includes(name)) state.categories.push(name); closeDialog(); saveRender(); }; }
function productDialog(id) { const product = state.products.find(item => String(item.id) === String(id)); dialog(`<div class="dialog-head"><span class="category-icon">PROD</span><h2>${product ? 'Editar produto' : 'Novo produto'}</h2><p>Preencha foto, categoria, descrição e preço.</p></div><form id="product-form" class="dialog-form"><label class="photo-picker">+<span>Adicionar foto<input name="photo" type="file" accept="image/*"></span></label><label>Nome do produto<input name="name" required value="${esc(product?.name || '')}" placeholder="Ex.: X-Bacon especial"></label><label>Categoria<select name="category" required>${state.categories.map(category => `<option ${product?.category === category ? 'selected' : ''}>${esc(category)}</option>`).join('')}</select></label><label>Descrição<textarea name="description" required placeholder="Conte os ingredientes.">${esc(product?.description || '')}</textarea></label><label>Preço<input name="price" type="number" step="0.01" min="0.01" required value="${product?.price || ''}" placeholder="0,00"></label><button class="primary-button">${product ? 'Salvar produto' : 'Adicionar ao cardápio'}</button></form>`); document.querySelector('#product-form').onsubmit = event => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const finish = photo => { const next = { id: product?.id || Date.now(), name: data.get('name').trim(), category: data.get('category'), description: data.get('description').trim(), price: Number(data.get('price')), photo: photo || product?.photo || null, emoji: 'FOOD', available: product?.available ?? true }; if (product) Object.assign(product, next); else state.products.push(next); closeDialog(); saveRender(); notify('Produto salvo no cardápio'); }; const file = form.querySelector('[name=photo]').files[0]; file ? fileData(file, finish) : finish(null); }; }
function fileData(file, callback) { if (!file) return callback(null); const reader = new FileReader(); reader.onload = () => callback(reader.result); reader.readAsDataURL(file); }
function sendMessage(event) { event.preventDefault(); const input = event.currentTarget.elements.message; state.messages.push({ from: 'merchant', text: input.value.trim(), time: new Date().toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }) }); input.value = ''; saveRender(); }
function cartDialog() { const total = state.cart.reduce((sum, item) => sum + item.price * item.quantity, 0); dialog(`<div class="dialog-head"><span class="category-icon">CAR</span><h2>Sua sacola</h2><p>Deixe um recado para a cozinha em cada item.</p></div><div class="cart-items">${state.cart.length ? state.cart.map(item => `<div class="cart-item"><span>${item.photo ? `<img src="${item.photo}" alt="">` : item.emoji}</span><div><strong>${esc(item.name)}</strong><small>${money(item.price)} · ${item.quantity}x</small><label class="note-field"><span>OBSERVACOES DO ITEM</span><input data-note="${item.id}" value="${esc(item.notes)}" placeholder="Ex.: sem cebola, bem passado..."><small>Opcional - a loja vera este recado no pedido</small></label></div></div>`).join('') : '<p class="empty-cart">Sua sacola está vazia.</p>'}</div>${state.cart.length ? `<div class="cart-total"><span>Total estimado</span><strong>${money(total)}</strong></div><button class="primary-button checkout-button">Continuar para entrega</button>` : ''}`); document.querySelectorAll('[data-note]').forEach(input => input.oninput = () => { state.cart.find(item => String(item.id) === input.dataset.note).notes = input.value; }); document.querySelector('.checkout-button')?.addEventListener('click', checkoutDialog); }
function checkoutDialog() { closeDialog(); dialog(`<div class="dialog-head"><span class="category-icon">?R</span><h2>Finalizar pedido</h2><p>O cliente não precisa criar conta.</p></div><form id="checkout-form" class="dialog-form"><label>Seu nome<input name="customer" required placeholder="Como podemos chamar você?"></label><label>Endereço de entrega<input name="address" required placeholder="Rua, número e complemento"></label><label>Pagamento<select name="payment"><option>Pix</option><option>Cartão na entrega</option><option>Dinheiro</option></select></label><button class="primary-button">Enviar pedido</button></form>`); document.querySelector('#checkout-form').onsubmit = event => { event.preventDefault(); const data = new FormData(event.currentTarget); state.orders.push({ id: `#${Date.now().toString().slice(-4)}`, customer: data.get('customer'), address: data.get('address'), payment: data.get('payment'), total: state.cart.reduce((sum, item) => sum + item.price * item.quantity, 0), status: 'Aguardando', notes: state.cart.map(item => item.notes).filter(Boolean).join(' | '), time: 'agora' }); state.cart = []; save(); closeDialog(); notify('Pedido enviado para a loja!'); shopView(); }; }
function customerChat() { dialog(`<div class="dialog-head"><span class="category-icon">?R</span><h2>Falar com a loja</h2><p>Tire uma dúvida antes de fazer seu pedido.</p></div><div class="chat-messages compact">${state.messages.map(message => `<div class="message ${message.from === 'customer' ? 'mine' : ''}">${esc(message.text)}<small>${esc(message.time)}</small></div>`).join('') || empty('Nenhuma mensagem', 'A loja ainda não enviou mensagens.')}</div><form id="customer-chat" class="chat-compose"><input name="message" required placeholder="Escreva sua dúvida..."><button>Enviar</button></form>`); document.querySelector('#customer-chat').onsubmit = event => { event.preventDefault(); const input = event.currentTarget.elements.message; state.messages.push({ from: 'customer', text: input.value.trim(), time: new Date().toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' }) }); save(); closeDialog(); notify('Mensagem enviada para a loja'); }; }

render();
